<?php

return array (
  'newUser' =>
  array (
    'subject' => 'Welcome to',
    'text' => 'Your account has been created successfully.',
  ),
  'loginAccount' => 'Login to your account',
  'hello' => 'Hello',
  'regards' => 'Regards',
  'thankyouNote' => 'Thank you',
  'newBooking' =>
  array (
    'subject' => 'New booking received.',
    'text' => 'Booking details are as follows',
  ),
  'bookingCancel' =>
  array (
    'subject' => 'Booking canceled by customer.',
    'text' => 'Booking has been canceled by :user. Canceled booking details are as follows.',
  ),
  'bookingReminder' =>
  array (
    'subject' => 'Booking reminder',
    'text' => 'You have a booking with us at',
  ),
  'bookingConfirmation' =>
  array (
    'subject' => 'Booking confirmed',
    'text' => 'Your booking is received successfully. Booking details are',
  ),
  'newContact' =>
  array (
    'subject' => 'New Contact Email',
  ),
  'bookingStatusUpdated' =>
  array (
    'text' => 'Your booking status has been updated to',
    'bookingDetails' => 'Booking details are',
    'subject' => 'Booking Status Updated',
  ),
  'newLeave' =>
  array (
    'fromDate' => 'Leave applied for date : ',
    'toDate' => 'To date : ',
    'fromTime' => 'Leave applied From time : ',
    'leave_type' => 'Leave type : ',
    'toTime' => 'To time : ',
    'leaveDetails' => 'A Leave application generated by',
    'subject' => 'Leave application received',
    'subjects' => 'Leave application',
    'approve' => 'Approve',
    'reject' => 'Reject',
    'reason' => 'Reason : ',
    'note' => 'Your Leave application has been',
    'details' => 'Your Leave details are :',
  ),
  'test' =>
  array(
    'subject' => 'Test email!',
    'text' => 'This is a test email.',
  ),
);
