<?php

return array (
  'search' =>
  array (
    'searchBy' => 'Search location, category, service, customer, employee, front page',
    'result' => 'Search Result For ":key"',
    'count' => 'About :count result',
    'noResultFound' => 'No Result Found',
    'searchHere' => 'Search Here',
    'pos' => 'Search',
  ),
  'update' =>
  array (
    'newUpdate' => 'New update available',
    'systemDetails' => 'System Details',
    'updateTitle' => 'Update To New Version',
    'updateDatabase' => 'Update Database',
    'fileReplaceAlert' => 'To update the app to new version check documentation for the instructions.',
    'updateDatabaseButton' => 'Click to update database',
    'updateNow' => 'Update Now',
    'updateAlternate' => 'If the Update Now button does not work then follow the update instructions as mentioned in the documentation.',
  ),
  'booking' =>
  array (
    'sendReminder' => 'Send Reminder',
    'addItemsToCart' => 'Add item to cart.',
    'changePaymentStatus' => 'Change Payment Status to Completed?',
    'requestCancellation' => 'Cancel Booking',
    'selectNote' => 'Click booking to select it.',
    'selectCustomer' => 'Select Customer',
    'paystackError' => 'There was an error please reload this page.',
    'customerDetails' => 'Customer Details',
    'searchNote' => 'Search a customer by name, email or mobile',
    'payViaCash' => 'Pay by cash',
    'payViaCard' => 'Pay by card',
    'cashGivenByCustomer' => 'Cash given by customer',
    'cashToReturn' => 'Cash to return',
    'cashRemaining' => 'Cash remaining',
    'emptyCart' => 'Empty Cart',
    'paymentMethod' => 'Payment Method',
    'paymentStatus' => 'Payment Status',
    'billedTo' => 'Billed To',
    'generatedBy' => 'Generated By',
    'earning' => 'Earning',
    'feedbackMessage' => 'Feedback Message',
    'additionalNote' => 'Additional Note',
    'changeStatus' => 'Change Status',
    'selectStatus' => 'Select Status',
    'selectLocation' => 'Select Location',
    'assignEmployee' => 'Assign Employee',
    'sortBy' => 'Sort By',
    'close' => 'Close',
    'giveFeedback' => 'Share Your Experience With Us',
    'sort' =>
    array (
      'desc' => 'Newest',
      'asc' => 'Oldest',
    ),
    'followingEmployeesAreAvailable' => 'Following employees are available',
    'sorry' => 'Sorry',
    'NoEmployeeAvailable' => 'No employee available',
    'selectEmployee' => 'Select Employee',
  ),
  'customer' =>
  array (
    'search' => 'Search customer by name, email or phone',
    'since' => 'Customer Since',
    'bookingStats' => 'Booking Stats',
    'contactInfo' => 'Contact Information',
  ),
  'theme' =>
  array (
    'defaultCssMessage' => '/*Enter your custom css after this line*/',
    'primaryColor' => 'Primary Color',
    'secondaryColor' => 'Secondary Color',
    'sidebarBgColor' => 'Sidebar Background Color',
    'sidebarTextColor' => 'Sidebar Text Color',
    'topbarTextColor' => 'Topbar Text Color',
    'theme' => 'Theme',
    'subheadings' =>
    array (
      'colorPallette' => 'Color Pallette',
      'carouselImages' => 'Carousel Images',
      'customCss' => 'Custom CSS',
      'selectTheme' => 'Select front theme for website',
    ),
    'recommendedResolutionNote' => '** Recommended image resolution: 1920 * 1080',
  ),
  'paymentCredential' =>
  array (
    'paypalCredentialStatus' => 'Paypal Credential Status',
    'stripeCredentialStatus' => 'Stripe Credential Status',
    'razorpayCredentialStatus' => 'RazorPay Credential Status',
    'changeCurrencyToINR' => 'Please change your default currency to INR to use RazorPay',
    'paypalClientID' => 'Paypal Client ID',
    'stripelClientID' => 'Publishable key',
    'paypalSecret' => 'Paypal Secret',
    'stripeSecret' => 'Secret key',
    'paypalCredential' => 'Paypal Credential',
    'stripeCredential' => 'Stripe Credential',
    'deactive' => 'Deactive',
    'active' => 'Active',
    'stripeWebhookSecret' => 'Stripe Webhook Secret',
    'allowOfflinePayment' => 'Allow Offline Payment',
    'razorpayKey' => 'RazorPay Key',
    'razorpaySecret' => 'RazorPay Secret',
    'paypalMode' => 'Paypal Mode',
    'allowCustomerPayment' => 'Allow Customer to Pay from Account',
    'payStackCredential' => 'Paystack Credential',
    'payStackCredentialStatus' => 'Paystack Credential status',
    'payStackPublicKey' => 'Paystack Public Key',
    'payStackSecretKey' => 'Paystack Secret Key',
    'payStackwebhook' => 'Paystack Webhook Secret',
  ),
  'nexmoCredential' =>
  array (
    'status' => 'Nexmo Status',
    'key' => 'Nexmo Key',
    'secret' => 'Nexmo Secret',
    'from' => 'Nexmo From',
    'active' => 'Active',
    'deactive' => 'Deactive',
  ),
  'msg91Credential' =>
  array (
    'status' => 'Msg91 Status',
    'key' => 'Msg91 Key',
    'from' => 'Msg91 Sender ID',
    'active' => 'Active',
    'deactive' => 'Deactive',
  ),
  'settings' =>
  array (
    'maxBookingAllowedInfo' => 'Set 0 for unlimited number of bookings',
    'language' =>
    array (
      'defaultLanguageCannotBeModified' => 'Default language cannot be updated or deleted.',
      'statusDisabledNote' => 'Cannot change status of Active Language',
    ),
    'openTime' => 'Open Time',
    'closeTime' => 'Close Time',
    'allowBooking' => 'Allow booking',
    'allowMultipleBooking' => 'Allow multiple bookings for same date and time?',
    'slotDuration' => 'Slot Duration',
    'maxBookingAllowed' => 'Maximum Number of Booking Allowed',
    'maxBookingAllowedPerDay' => 'Maximum Number of Booking Allowed Per Day',
    'maxBookingAllowedPerSlot' => 'Maximum Number of Booking Allowed Per Slot',


  ),
  'rolePermission' =>
  array (
    'forms' =>
    array (
      'addMembers' => 'Add Members',
      'displayName' => 'Role Name',
      'name' => 'Name',
      'description' => 'Description',
    ),
    'addRole' => 'Add Role',
    'members' => 'Members',
    'permissions' => 'Permissions',
    'selectAll' => 'Select All',
    'manageRole' => 'Manage Role',
    'addMember' => 'Add member',
    'manageMembers' => 'Manage Members',
    'editRole' => 'Edit Role',
    'tables' =>
    array (
      'roleDescription' => 'Role Description',
      'roleName' => 'Role Name',
      'memberName' => 'Member Name',
      'memberRole' => 'Member Role',
    ),
  ),
  'services' =>
  array (
    'percent' => 'percent',
    'fixed' => 'fixed',
    'time' => 'Time required',
    'minutes' => 'Minutes',
    'discount' => 'Discount',
    'discountedPrice' => 'Price after discount',
  ),
  'module' =>
  array (
    'todos' =>
    array (
      'todoList' => 'ToDo List',
      'viewAll' => 'View All',
      'noPendingTasks' => 'No pending tasks are available!',
      'noCompletedTasks' => 'No tasks are marked as completed.',
      'pending' => 'Pending',
      'completed' => 'Completed',
      'pendingTasks' => 'Pending Tasks',
      'completedTasks' => 'Completed Tasks',
      'createTodoItem' => 'Create ToDo Item',
      'editTodoItem' => 'Edit ToDo Item',
      'form' =>
      array (
        'title' => 'Title',
        'status' => 'Status',
      ),
    ),
    'pointOfSaleDescription' => 'User with this permission have full access to booking module.',
    'settingsDescription' => 'User with this permission have full access to manage settings.',
    'bookingDescription' => 'User with Booking Add permission have access to POS module.',
  ),
  'datatables' =>
  array (
    'processing' => 'Processing...',
    'search' => 'Search:',
    'lengthMenu' => 'Show _MENU_ entries',
    'info' => 'Showing _START_ to _END_ of _TOTAL_ entries',
    'infoEmpty' => 'Showing 0 to 0 of 0 entries',
    'infoFiltered' => '(filtered from _MAX_ total entries)',
    'infoPostFix' => '',
    'loadingRecords' => 'Loading...',
    'zeroRecords' => 'No matching records found',
    'emptyTable' => 'No data available in table',
    'paginate' =>
    array (
      'first' => 'First',
      'previous' => 'Previous',
      'next' => 'Next',
      'last' => 'Last',
    ),
    'aria' =>
    array (
      'sortAscending' => ': activate to sort column ascending',
      'sortDescending' => ': activate to sort column descending',
    ),
    'infoThousands' => ',',
  ),
  'emailSettings' =>
  array (
    'mailDriver' => 'Mail Driver',
    'mailHost' => 'Mail Host',
    'mailPort' => 'Mail Port',
    'mailUsername' => 'Mail Username',
    'mailPassword' => 'Mail Password',
    'mailFrom' => 'Mail From Name',
    'mailFromEmail' => 'Mail From Email',
    'mailEncryption' => 'Mail Encryption',
  ),
  'dashboard' =>
  array (
    'totalBooking' => 'Total Bookings',
    'pendingBooking' => 'Pending Bookings',
    'completedBooking' => 'Completed Bookings',
    'canceledBooking' => 'Canceled Bookings',
    'totalCustomers' => 'Total Customers',
    'totalEarning' => 'Total Earnings',
    'recentBookings' => 'Recent Bookings',
    'walkInBookings' => 'Walk-In Bookings',
    'onlineBookings' => 'Online Bookings',
    'inProgressBooking' => 'In Progress Bookings',
    'approvedBooking' => 'Approved Bookings',
  ),
  'businessServices' =>
  array (
    'defaultImageNotice' => '** First uploaded image would be default one.',
  ),
  'close' => 'Close',
  'leaves' =>
  array (
    'applicantName' => 'Applicant Name',
    'reason' => 'Reason for absence',
    'type' => 'Leave Type',
    'approvedBy' => 'Approved By',
    'rejectedBy' => 'Rejected By',
  ),
  'frontCms' =>
  array (
    'socialLinks' => 'Social Links',
    'socialLinksNote' => 'Note: Leave input blank to hide it on Home Page.',
    'footerText' => 'Footer Text',
    'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'instagram' => 'Instagram',
    'youtube' => 'youtube',
    'linkedin' => 'LinkedIn',
    'enterFacebookLink' => 'Enter Facebook Link',
    'enterTwitterLink' => 'Enter Twitter Link',
    'enterInstagramLink' => 'Enter Instagram Link',
    'enterYoutubeLink' => 'Enter Youtube Link',
    'enterLinkedinLink' => 'Enter LinkedIn Link',
  ),
  'type' => 'Type',
  'timecronjob' => 'Select time before you want to notify customer'
);
